export const TEMPLATES = [
    {
        id: 'south-indian',
        name: 'South Indian',
        emoji: '🪷',
        description: 'Traditional silk saree, temple jewelry setting with warm golden lighting',
        modelPrompt: 'A beautiful South Indian woman wearing a rich Kanjivaram silk saree in deep maroon and gold, with traditional temple-style hair adorned with jasmine flowers (gajra), standing in an ornate temple corridor with carved stone pillars',
        settingPrompt: 'traditional South Indian temple with golden oil lamps, intricate gopuram architecture in the background, marigold flower decorations',
        lightingPrompt: 'warm golden hour lighting with soft divine glow, oil lamp reflections, rich warm tones emphasizing gold and maroon colors',
        posePrompt: 'natural relaxed pose that best showcases the jewelry, elegant and graceful posture',
    },
    {
        id: 'north-indian',
        name: 'North Indian',
        emoji: '🏯',
        description: 'Lehenga or salwar, Mughal-inspired backdrop with rich jewel tones',
        modelPrompt: 'A stunning North Indian woman wearing an embroidered royal blue and gold lehenga with intricate zardozi work, hair styled in a side braid with maang tikka',
        settingPrompt: 'grand Mughal palace interior with ornate marble arches, jharokha window with lattice work, soft silk curtains, palatial garden visible through arched doorways',
        lightingPrompt: 'regal ambient lighting with warm candelabra glow, soft shadows through marble jali screens, rich jewel-toned color palette',
        posePrompt: 'natural elegant pose that highlights the jewelry, confident and graceful expression',
    },
    {
        id: 'american',
        name: 'American',
        emoji: '🗽',
        description: 'Modern cocktail dress, clean studio setting with neutral tones',
        modelPrompt: 'A sophisticated American woman wearing an elegant black cocktail dress with a plunging neckline, hair styled in loose Hollywood waves',
        settingPrompt: 'minimalist high-end photography studio with clean white backdrop, subtle grey gradient, a single velvet stool or pedestal',
        lightingPrompt: 'professional studio lighting with key light and fill light, crisp highlights on jewelry, clean white reflections, fashion editorial look',
        posePrompt: 'modern natural pose that showcases the jewelry best, confident elegant expression',
    },
    {
        id: 'european',
        name: 'European',
        emoji: '🏰',
        description: 'Elegant gown, classical marble setting with soft romantic lighting',
        modelPrompt: 'An elegant European woman wearing a flowing champagne-colored silk gown with off-shoulder design, hair in an elegant updo with a few loose tendrils',
        settingPrompt: 'grand European palace salon with marble columns, gilded mirrors, crystal chandelier, Renaissance oil paintings on the walls, velvet drapery',
        lightingPrompt: 'soft romantic chandelier lighting, warm amber tones with cool marble reflections, Rembrandt-style dramatic light and shadow',
        posePrompt: 'refined natural pose that highlights the jewelry beautifully, sophisticated serene expression',
    },
    {
        id: 'custom',
        name: 'Custom',
        emoji: '✨',
        description: 'Define your own model, setting, and style',
        modelPrompt: '',
        settingPrompt: '',
        lightingPrompt: '',
        posePrompt: '',
    },
    {
        id: 'custom-model',
        name: 'Custom Model (Nill)',
        emoji: '👤',
        description: 'Upload your own model photo — keeps the model unchanged, only adds jewelry',
        modelPrompt: 'Use the uploaded model reference photo exactly as-is — same person, same face, same skin tone, same body proportions, same hair style and color, same outfit, same background. The model and the entire scene must remain completely unchanged.',
        settingPrompt: 'Keep the exact same background, setting, and environment from the uploaded model reference photo. No changes to the scene whatsoever.',
        lightingPrompt: 'Preserve the exact same lighting conditions from the uploaded model reference photo. Maintain the same shadows, highlights, and overall illumination.',
        posePrompt: 'Keep the exact same pose, expression, and body position from the uploaded model reference photo. The model should not move or change position at all.',
    },
];

export function getTemplateById(id) {
    return TEMPLATES.find(t => t.id === id) || TEMPLATES[0];
}
